---

- name: "Log into private registry and force re-authorization"
  docker_login:
    registry: "{{ registry }}"
    cacert_path: "{{ playbook_dir }}/docker_certs.d/{{ registry }}/ca.crt"
    username: "admin"
    password: "admin"
    reauthorize: yes
  register: loginto_info

- debug: msg="{{ loginto_info }}"
